channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.1.3
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.12.0
name: mlflow-env
